import { getSupabaseClient, getSocialSession } from '@/lib/social/client';
import {
  createFallbackHandle,
  createSuggestedAvatarUrl,
  createSuggestedDisplayName,
  createSuggestedHandle,
  isSocialProfileComplete,
  nextHandleCandidate,
} from '@/lib/social/profile-defaults';
import { SocialProfile, UpsertSocialProfileInput } from '@/lib/social/types';

const DEFAULT_TIMEZONE = Intl.DateTimeFormat().resolvedOptions().timeZone;
const HANDLE_CONFLICT_ATTEMPTS = 8;

let pendingProfileDisplayName: string | null = null;

function mapProfileRow(row: Record<string, unknown>): SocialProfile {
  return {
    id: String(row.id),
    displayName: String(row.display_name ?? ''),
    handle: String(row.handle ?? ''),
    avatarUrl: typeof row.avatar_url === 'string' ? row.avatar_url : null,
    timezone: String(row.timezone ?? DEFAULT_TIMEZONE),
    allowCircleNotifications:
      typeof row.allow_circle_notifications === 'boolean' ? row.allow_circle_notifications : true,
    allowMissedAlarmAlerts:
      typeof row.allow_missed_alarm_alerts === 'boolean' ? row.allow_missed_alarm_alerts : true,
    createdAt: String(row.created_at ?? new Date().toISOString()),
    updatedAt: String(row.updated_at ?? new Date().toISOString()),
  };
}

function isHandleConflictError(error: unknown) {
  if (typeof error === 'object' && error && 'code' in error && (error as { code?: string }).code === '23505') {
    return true;
  }

  const message = error instanceof Error ? error.message : String(error);
  return /duplicate key|profiles_handle_key|already exists/i.test(message);
}

export function setPendingProfileDisplayName(displayName: string | null) {
  pendingProfileDisplayName = displayName?.trim() || null;
}

export function clearPendingProfileDisplayName() {
  pendingProfileDisplayName = null;
}

export async function getMySocialProfile() {
  const client = getSupabaseClient();
  const session = await getSocialSession();

  if (!client || !session?.user) {
    return null;
  }

  const { data, error } = await client
    .from('profiles')
    .select('*')
    .eq('id', session.user.id)
    .maybeSingle();

  if (error) {
    throw error;
  }

  return data ? mapProfileRow(data) : null;
}

export async function upsertMySocialProfile(input: UpsertSocialProfileInput) {
  const client = getSupabaseClient();
  const session = await getSocialSession();

  if (!client || !session?.user) {
    throw new Error('No authenticated social session found.');
  }

  const payload = {
    id: session.user.id,
    display_name: input.displayName.trim(),
    handle: input.handle.trim().toLowerCase(),
    avatar_url: input.avatarUrl ?? null,
    timezone: input.timezone,
    allow_circle_notifications: input.allowCircleNotifications,
    allow_missed_alarm_alerts: input.allowMissedAlarmAlerts,
  };

  const { data, error } = await client.from('profiles').upsert(payload).select('*').single();

  if (error) {
    throw error;
  }

  return mapProfileRow(data);
}

export async function ensureMySocialProfile() {
  const session = await getSocialSession();

  if (!session?.user) {
    return null;
  }

  const existingProfile = await getMySocialProfile();
  const suggestedDisplayName = createSuggestedDisplayName(session.user, pendingProfileDisplayName);
  const autoGeneratedDisplayName = createSuggestedDisplayName(session.user);
  const canUpgradeDisplayName = Boolean(
    pendingProfileDisplayName &&
      existingProfile &&
      existingProfile.displayName !== pendingProfileDisplayName &&
      (!existingProfile.displayName.trim() || existingProfile.displayName === autoGeneratedDisplayName)
  );

  if (isSocialProfileComplete(existingProfile) && !canUpgradeDisplayName) {
    return existingProfile;
  }

  const existingDisplayName = existingProfile?.displayName.trim() ?? '';
  const displayName = existingDisplayName && !canUpgradeDisplayName ? existingDisplayName : suggestedDisplayName;
  const existingHandle = existingProfile?.handle.trim().toLowerCase() ?? '';
  const baseHandle = existingHandle || createSuggestedHandle(session.user);
  const timezone = (existingProfile?.timezone ?? DEFAULT_TIMEZONE).trim() || DEFAULT_TIMEZONE;

  if (!displayName || !baseHandle) {
    return existingProfile;
  }

  let lastError: unknown = null;

  for (let attempt = 0; attempt < HANDLE_CONFLICT_ATTEMPTS; attempt += 1) {
    const handle = existingHandle
      ? existingHandle
      : attempt === HANDLE_CONFLICT_ATTEMPTS - 1
        ? createFallbackHandle(session.user.id)
        : nextHandleCandidate(baseHandle, attempt);

    try {
      return await upsertMySocialProfile({
        displayName,
        handle,
        avatarUrl: existingProfile?.avatarUrl ?? createSuggestedAvatarUrl(session.user),
        timezone,
        allowCircleNotifications: existingProfile?.allowCircleNotifications ?? true,
        allowMissedAlarmAlerts: existingProfile?.allowMissedAlarmAlerts ?? true,
      });
    } catch (error) {
      lastError = error;

      if (!isHandleConflictError(error) || existingHandle) {
        throw error;
      }
    }
  }

  throw lastError instanceof Error ? lastError : new Error('Your profile could not be created right now.');
}
