alter table public.user_alarms
add column if not exists timezone text not null default 'UTC',
add column if not exists schedule_revision integer not null default 1 check (schedule_revision > 0);

create index if not exists user_alarms_due_idx
on public.user_alarms (scheduled_for)
where is_active and scheduled_for is not null;

alter table public.alarm_events
add column if not exists occurrence_key text,
add column if not exists captured_at timestamptz,
add column if not exists schedule_revision integer not null default 1;

update public.alarm_events
set occurrence_key = alarm_id || '::' || coalesce(
  to_char(scheduled_for at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
  'unscheduled'
),
captured_at = coalesce(captured_at, resolved_at)
where occurrence_key is null or captured_at is null;

-- Older clients included the outcome in the event id, so consolidate the rare
-- case where both outcomes were written for one occurrence before enforcing the
-- occurrence-level uniqueness contract. Prefer a confirmed proof.
with ranked as (
  select
    id,
    row_number() over (
      partition by user_id, occurrence_key
      order by (outcome = 'confirmed') desc, resolved_at desc, created_at desc
    ) as rank
  from public.alarm_events
  where occurrence_key is not null
)
delete from public.alarm_events events
using ranked
where events.id = ranked.id and ranked.rank > 1;

alter table public.alarm_events
alter column occurrence_key set not null,
alter column captured_at set not null;

create unique index if not exists alarm_events_user_occurrence_idx
on public.alarm_events (user_id, occurrence_key);

create table if not exists public.alarm_outcome_revisions (
  id bigint generated by default as identity primary key,
  alarm_event_id text not null references public.alarm_events (id) on delete cascade,
  previous_outcome text not null check (previous_outcome in ('confirmed', 'missed')),
  next_outcome text not null check (next_outcome in ('confirmed', 'missed')),
  changed_at timestamptz not null default timezone('utc', now()),
  reason text not null,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.alarm_notification_outbox (
  id bigint generated by default as identity primary key,
  alarm_event_id text not null references public.alarm_events (id) on delete cascade,
  kind text not null check (kind in ('missed_checkpoint', 'outcome_correction')),
  revision integer not null default 1,
  created_at timestamptz not null default timezone('utc', now()),
  processed_at timestamptz,
  last_error text,
  unique (alarm_event_id, kind, revision)
);

create table if not exists public.alarm_notification_deliveries (
  outbox_id bigint not null references public.alarm_notification_outbox (id) on delete cascade,
  device_push_token_id uuid not null references public.device_push_tokens (id) on delete cascade,
  delivered_at timestamptz not null default timezone('utc', now()),
  primary key (outbox_id, device_push_token_id)
);

alter table public.alarm_outcome_revisions enable row level security;
alter table public.alarm_notification_outbox enable row level security;
alter table public.alarm_notification_deliveries enable row level security;

create policy "alarm_outcome_revisions_select_owner"
on public.alarm_outcome_revisions
for select
using (
  exists (
    select 1 from public.alarm_events events
    where events.id = alarm_outcome_revisions.alarm_event_id
      and events.user_id = auth.uid()
  )
);

create or replace function public.next_alarm_occurrence(
  hour_input integer,
  minute_input integer,
  repeat_schedule_input text,
  timezone_input text,
  after_input timestamptz
)
returns timestamptz
language plpgsql
stable
set search_path = public
as $$
declare
  local_after timestamp;
  local_candidate timestamp;
begin
  if repeat_schedule_input not in ('daily', 'weekdays') then
    return null;
  end if;

  begin
    local_after := after_input at time zone timezone_input;
  exception when invalid_parameter_value then
    timezone_input := 'UTC';
    local_after := after_input at time zone timezone_input;
  end;

  local_candidate := date_trunc('day', local_after)
    + make_interval(hours => hour_input, mins => minute_input);

  if local_candidate <= local_after then
    local_candidate := local_candidate + interval '1 day';
  end if;

  if repeat_schedule_input = 'weekdays' then
    while extract(isodow from local_candidate) in (6, 7) loop
      local_candidate := local_candidate + interval '1 day';
    end loop;
  end if;

  return local_candidate at time zone timezone_input;
end;
$$;

create or replace function public.resolve_alarm_occurrence(
  alarm_id_input text,
  scheduled_for_input timestamptz,
  outcome_input text,
  captured_at_input timestamptz,
  schedule_revision_input integer,
  metadata_input jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  owner_id uuid := auth.uid();
  alarm_row public.user_alarms%rowtype;
  event_row public.alarm_events%rowtype;
  occurrence_key_value text;
  deadline_at timestamptz;
  next_scheduled_for timestamptz;
  event_id_value text;
  social_settings_value jsonb;
  correction_revision integer;
begin
  if owner_id is null then
    raise exception 'Authentication required.';
  end if;

  if outcome_input not in ('confirmed', 'missed') then
    raise exception 'Unsupported alarm outcome.';
  end if;

  select * into alarm_row
  from public.user_alarms
  where user_id = owner_id and id = alarm_id_input
  for update;

  if not found then
    return jsonb_build_object('status', 'rejected', 'reason', 'alarm_not_found');
  end if;

  occurrence_key_value := alarm_id_input || '::' ||
    to_char(scheduled_for_input at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
  deadline_at := scheduled_for_input + make_interval(secs => alarm_row.grace_period_seconds);

  if outcome_input = 'confirmed' and captured_at_input > deadline_at then
    return jsonb_build_object('status', 'rejected', 'reason', 'proof_after_deadline');
  end if;

  select * into event_row
  from public.alarm_events
  where user_id = owner_id and occurrence_key = occurrence_key_value
  for update;

  social_settings_value := coalesce(metadata_input->'socialSettings', alarm_row.social_settings, '{}'::jsonb);

  if found then
    if event_row.outcome = outcome_input then
      return jsonb_build_object(
        'status', 'duplicate',
        'eventId', event_row.id,
        'scheduledFor', alarm_row.scheduled_for
      );
    end if;

    if event_row.outcome = 'missed' and outcome_input = 'confirmed' then
      insert into public.alarm_outcome_revisions (
        alarm_event_id, previous_outcome, next_outcome, reason, metadata
      ) values (
        event_row.id, 'missed', 'confirmed', 'valid_offline_proof', metadata_input
      );

      update public.alarm_events
      set outcome = 'confirmed',
          resolved_at = captured_at_input,
          captured_at = captured_at_input,
          source = 'device',
          share_successes = event_row.share_misses or coalesce((social_settings_value->>'shareSuccesses')::boolean, false),
          metadata = metadata_input
      where id = event_row.id
      returning * into event_row;

      update public.proof_shares
      set payload = payload || jsonb_build_object(
        'outcome', 'confirmed',
        'correctedAt', timezone('utc', now())
      )
      where alarm_event_id = event_row.id;

      select count(*)::integer into correction_revision
      from public.alarm_outcome_revisions
      where alarm_event_id = event_row.id;

      insert into public.alarm_notification_outbox (alarm_event_id, kind, revision)
      values (event_row.id, 'outcome_correction', correction_revision)
      on conflict do nothing;

      return jsonb_build_object(
        'status', 'corrected',
        'eventId', event_row.id,
        'scheduledFor', alarm_row.scheduled_for
      );
    end if;

    return jsonb_build_object('status', 'rejected', 'reason', 'outcome_already_confirmed');
  end if;

  event_id_value := owner_id::text || '::' || occurrence_key_value;
  insert into public.alarm_events (
    id, user_id, alarm_id, alarm_label, occurrence_key, scheduled_for,
    outcome, resolved_at, captured_at, schedule_revision, source, circle_id,
    share_successes, share_misses, metadata
  ) values (
    event_id_value, owner_id, alarm_row.id, alarm_row.label, occurrence_key_value, scheduled_for_input,
    outcome_input, captured_at_input, captured_at_input, schedule_revision_input, 'device',
    nullif(social_settings_value->>'circleId', '')::uuid,
    coalesce((social_settings_value->>'shareSuccesses')::boolean, false),
    coalesce((social_settings_value->>'shareMisses')::boolean, false), metadata_input
  ) returning * into event_row;

  if event_row.circle_id is not null and (
    (outcome_input = 'confirmed' and event_row.share_successes) or
    (outcome_input = 'missed' and event_row.share_misses)
  ) then
    insert into public.proof_shares (alarm_event_id, user_id, circle_id, payload)
    values (event_row.id, owner_id, event_row.circle_id, metadata_input)
    on conflict (alarm_event_id, circle_id) do update set payload = excluded.payload;
  end if;

  if outcome_input = 'missed' and event_row.share_misses then
    insert into public.alarm_notification_outbox (alarm_event_id, kind)
    values (event_row.id, 'missed_checkpoint')
    on conflict do nothing;
  end if;

  if alarm_row.scheduled_for = scheduled_for_input and alarm_row.schedule_revision = schedule_revision_input then
    if alarm_row.repeat_schedule = 'once' then
      update public.user_alarms
      set is_active = false, last_outcome = outcome_input
      where user_id = owner_id and id = alarm_row.id;
      next_scheduled_for := scheduled_for_input;
    else
      next_scheduled_for := public.next_alarm_occurrence(
        alarm_row.hour,
        alarm_row.minute,
        alarm_row.repeat_schedule,
        alarm_row.timezone,
        scheduled_for_input
      );
      update public.user_alarms
      set scheduled_for = next_scheduled_for, last_outcome = outcome_input
      where user_id = owner_id and id = alarm_row.id;
    end if;
  else
    next_scheduled_for := alarm_row.scheduled_for;
  end if;

  return jsonb_build_object(
    'status', 'created',
    'eventId', event_row.id,
    'scheduledFor', next_scheduled_for
  );
end;
$$;

revoke all on function public.resolve_alarm_occurrence(text, timestamptz, text, timestamptz, integer, jsonb) from public;
grant execute on function public.resolve_alarm_occurrence(text, timestamptz, text, timestamptz, integer, jsonb) to authenticated;

create or replace function public.claim_due_alarm_occurrences(batch_size_input integer default 100)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  alarm_row public.user_alarms%rowtype;
  occurrence_key_value text;
  event_id_value text;
  social_settings_value jsonb;
  claimed_count integer := 0;
  next_scheduled_for timestamptz;
begin
  for alarm_row in
    select * from public.user_alarms
    where is_active
      and scheduled_for is not null
      and scheduled_for + make_interval(secs => grace_period_seconds) < timezone('utc', now())
    order by scheduled_for
    for update skip locked
    limit greatest(1, least(batch_size_input, 500))
  loop
    occurrence_key_value := alarm_row.id || '::' ||
      to_char(alarm_row.scheduled_for at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
    event_id_value := alarm_row.user_id::text || '::' || occurrence_key_value;
    social_settings_value := coalesce(alarm_row.social_settings, '{}'::jsonb);

    insert into public.alarm_events (
      id, user_id, alarm_id, alarm_label, occurrence_key, scheduled_for,
      outcome, resolved_at, captured_at, schedule_revision, source, circle_id,
      share_successes, share_misses, metadata
    ) values (
      event_id_value, alarm_row.user_id, alarm_row.id, alarm_row.label,
      occurrence_key_value, alarm_row.scheduled_for, 'missed',
      alarm_row.scheduled_for + make_interval(secs => alarm_row.grace_period_seconds),
      alarm_row.scheduled_for + make_interval(secs => alarm_row.grace_period_seconds),
      alarm_row.schedule_revision, 'server',
      nullif(social_settings_value->>'circleId', '')::uuid,
      coalesce((social_settings_value->>'shareSuccesses')::boolean, false),
      coalesce((social_settings_value->>'shareMisses')::boolean, false),
      jsonb_build_object('gracePeriodSeconds', alarm_row.grace_period_seconds)
    ) on conflict (user_id, occurrence_key) do nothing;

    if found and coalesce((social_settings_value->>'shareMisses')::boolean, false) then
      insert into public.proof_shares (alarm_event_id, user_id, circle_id, payload)
      select event_id_value, alarm_row.user_id, nullif(social_settings_value->>'circleId', '')::uuid,
        jsonb_build_object('gracePeriodSeconds', alarm_row.grace_period_seconds)
      where nullif(social_settings_value->>'circleId', '') is not null
      on conflict (alarm_event_id, circle_id) do nothing;

      insert into public.alarm_notification_outbox (alarm_event_id, kind)
      values (event_id_value, 'missed_checkpoint')
      on conflict do nothing;
    end if;

    if alarm_row.repeat_schedule = 'once' then
      update public.user_alarms
      set is_active = false, last_outcome = 'missed'
      where user_id = alarm_row.user_id and id = alarm_row.id;
    else
      next_scheduled_for := public.next_alarm_occurrence(
        alarm_row.hour, alarm_row.minute, alarm_row.repeat_schedule,
        alarm_row.timezone, alarm_row.scheduled_for
      );
      update public.user_alarms
      set scheduled_for = next_scheduled_for, last_outcome = 'missed'
      where user_id = alarm_row.user_id and id = alarm_row.id;
    end if;

    claimed_count := claimed_count + 1;
  end loop;

  return claimed_count;
end;
$$;

revoke all on function public.claim_due_alarm_occurrences(integer) from public, anon, authenticated;
grant execute on function public.claim_due_alarm_occurrences(integer) to service_role;

-- Intentionally no cron.schedule call here. Enable the minute schedule only
-- after the occurrence-aware mobile release is the minimum supported version.
